const INPUT = {
    CONTROLLER_1: {
        A : 'A',
        C : 'C',
        I : 'I',
        P : 'P',
        Z : 'Z',
        O : 'O',
        B : 'B',
        M : 'M',
        N : 'N',
        S : 'S',
        ONE : '1',
        TWO : '2',
        THREE : '3',
        FOUR : '4',
        FIVE : '5',
        SIX : '6',
        SEVEN : '7',
        EIGHT : '8',
        TIME : '/',
        ROTATE : ',',
        SPACE : 'space',
        ENTER : 'enter',
        TAB : 'tab',
        HOME : 'home',
        END : 'end',
        PGUP : 'pageup',
        PGDN : 'pagedown',
        HELP : 'F1',
        SAVE : 'F6',
        LOAD : 'F7',
        ESC  : 'escape'
    },
    CONTROLLER_2: {
        A : 'A',
        C : 'C',
        I : 'I',
        P : 'P',
        Z : 'Z',
        O : 'O',
        B : 'B',
        M : 'M',
        N : 'N',
        S : 'S',
        ONE : '1',
        TWO : '2',
        THREE : '3',
        FOUR : '4',
        FIVE : '5',
        SIX : '6',
        SEVEN : '7',
        EIGHT : '8',
        TIME : '/',
        ROTATE : ',',
        SPACE : 'space',
        ENTER : 'enter',
        TAB : 'tab',
        HOME : 'home',
        END : 'end',
        PGUP : 'pageup',
        PGDN : 'pagedown',
        HELP : 'F1',
        SAVE : 'F6',
        LOAD : 'F7',
        ESC  : 'escape'
    },
};

module.exports = {
    INPUT,
};