const INPUT = {
    CONTROLLER_1: {
        // UP: 'up',
        // DOWN: 'down',
        // LEFT: 'left',
        // RIGHT: 'right',
        // A: 'a',
        // B: 'b',
        // X: 'x',
        // Y: 'y',
        // LTRIG: 'l',
        // RTRIG: 'r',
        // SELECT: '-',
        // START: '=',
        A : 'A',
        C : 'C',
        I : 'I',
        P : 'P',
        Z : 'Z',
        O : 'O',
        B : 'B',
        M : 'M',
        N : 'N',
        S : 'S',
        1 : '1',
        2 : '2',
        3 : '3',
        4 : '4',
        5 : '5',
        6 : '6',
        7 : '7',
        8 : '8',
        TIME : '?',
        ROTATE : '<',
        SPACE : 'SPACE',
        ENTER : 'ENTER',
        TAB : 'TAB',
        HOME : 'HOME',
        END : 'END',
        PGUP : 'PGUP',
        PGDN : 'PGDN',
        HELP : 'HELP',
        SAVE : 'SAVE',
        LOAD : 'LOAD',
    },
    // CONTROLLER_2: {
    //     UP: 'numpad_8',
    //     DOWN: 'numpad_2',
    //     LEFT: 'numpad_4',
    //     RIGHT: 'numpad_6',
    //     A: 'numpad_7',
    //     B: 'numpad_9',
    //     X: 'numpad_1',
    //     Y: 'numpad_3',
    //     LTRIG: 'numpad_0',
    //     RTRIG: 'numpad_.',
    //     SELECT: '[',
    //     START: ']',
    // },
};

module.exports = {
    INPUT,
};